server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ZMS_USR?serverTimezone=Asia/Taipei&characterEncoding=utf-8
    username: root
    password: 06494784
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-service